### PR TITLE
Split DFD and Web Converter

### LINKED ISSUE #217: Split WebToDfd and DfdToWeb in seperate classes
The `DataFlowDiagramConverter`class has gotten very big (around 600 loc) and contains both Web2Dfd and Dfd2Web.
This is, on the one hand, hard to navigate, and on the other hand, it leads to methods like `createNodes` and `createWebNodes`, where it is unclear which belongs to which direction.
Therefore we should split this class into a `DataFlowDiagramConverter` and a `WebEditorConverter`

### PR DESCRIPTION
**Pull request by uuqjz**
This PR splits the 750 loc DFDConverter into a DFDConverter (dfdToWeb) and a WebEditorConverter(webToDfd)

### CODE REVIEW

**Comment by 01Parzival10** [comment]
I suggest moving the storeWeb method from the DataFlowDiagramConverter to the Converter class and making it static.

Or move the storeDFD method to the WebEditorConverter Class and get completely rid of the Converter class.

**Comment by uuqjz** [comment]
> I suggest moving the storeWeb method from the DataFlowDiagramConverter to the Converter class and making it static.
> 
> Or move the storeDFD method to the WebEditorConverter Class and get completely rid of the Converter class.

`storeDFD`is also used by the PCM converter. So I'd rather go with the first option

**Comment by uuqjz** [comment]
@01Parzival10 Done.

**Review by Nicolas-Boltz — APPROVED** [review]
LGTM. I think it was a very wise decision to split up the editor.

**Pull request merged**
